<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210143651 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE genres (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_genres_parent ON genres (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_genres_slug ON genres (slug)');
        $this->addSql('ALTER TABLE genres ADD CONSTRAINT FK_A8EBE516727ACA70 FOREIGN KEY (parent_id) REFERENCES genres (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_genres DROP CONSTRAINT fk_98c901739557e6f6');
        $this->addSql('ALTER TABLE post_genres DROP CONSTRAINT post_genres_pkey');
        $this->addSql('DROP INDEX idx_98c901739557e6f6');
        $this->addSql('ALTER TABLE post_genres RENAME COLUMN taxonomy_id TO genre_id');
        $this->addSql('ALTER TABLE post_genres ADD CONSTRAINT FK_98C901734296D31F FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_98C901734296D31F ON post_genres (genre_id)');
        $this->addSql('ALTER TABLE post_genres ADD PRIMARY KEY (post_id, genre_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE genres DROP CONSTRAINT FK_A8EBE516727ACA70');
        $this->addSql('DROP TABLE genres');
        $this->addSql('ALTER TABLE post_genres DROP CONSTRAINT FK_98C901734296D31F');
        $this->addSql('DROP INDEX IDX_98C901734296D31F');
        $this->addSql('ALTER TABLE post_genres DROP CONSTRAINT post_genres_pkey');
        $this->addSql('ALTER TABLE post_genres RENAME COLUMN genre_id TO taxonomy_id');
        $this->addSql('ALTER TABLE post_genres ADD CONSTRAINT fk_98c901739557e6f6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomies (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_98c901739557e6f6 ON post_genres (taxonomy_id)');
        $this->addSql('ALTER TABLE post_genres ADD PRIMARY KEY (post_id, taxonomy_id)');
    }
}
