<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates users, posts, and pages tables with proper indexes and relationships.
 * Drops the legacy article table which is replaced by the posts table.
 */
final class Version20260125215823 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users, posts, and pages tables; drop article table';
    }

    public function up(Schema $schema): void
    {
        // Create users table
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(100) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)');

        // Create pages table
        $this->addSql('CREATE TABLE pages (title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(500) DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, depublished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2074E575989D9B62 ON pages (slug)');
        $this->addSql('CREATE INDEX idx_pages_status ON pages (status)');
        $this->addSql('CREATE INDEX idx_pages_author_id ON pages (author_id)');
        $this->addSql('ALTER TABLE pages ADD CONSTRAINT FK_2074E575F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');

        // Create posts table
        $this->addSql('CREATE TABLE posts (title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, excerpt VARCHAR(500) DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, depublished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_885DBAFA989D9B62 ON posts (slug)');
        $this->addSql('CREATE INDEX idx_posts_status ON posts (status)');
        $this->addSql('CREATE INDEX idx_posts_author_id ON posts (author_id)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAF675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');

        // Drop legacy article table
        $this->addSql('DROP TABLE article');
    }

    public function down(Schema $schema): void
    {
        // Recreate article table
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, PRIMARY KEY (id))');

        // Drop posts table
        $this->addSql('ALTER TABLE posts DROP CONSTRAINT FK_885DBAFAF675F31B');
        $this->addSql('DROP TABLE posts');

        // Drop pages table
        $this->addSql('ALTER TABLE pages DROP CONSTRAINT FK_2074E575F675F31B');
        $this->addSql('DROP TABLE pages');

        // Drop users table
        $this->addSql('DROP TABLE users');
    }
}
