<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260309122406 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE page_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content TEXT DEFAULT NULL, object_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78AB76C9232D562B ON page_translations (object_id)');
        $this->addSql('CREATE UNIQUE INDEX page_translation_unique_idx ON page_translations (locale, object_id, field)');
        $this->addSql('CREATE TABLE post_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content TEXT DEFAULT NULL, object_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D8AA754232D562B ON post_translations (object_id)');
        $this->addSql('CREATE UNIQUE INDEX post_translation_unique_idx ON post_translations (locale, object_id, field)');
        $this->addSql('ALTER TABLE page_translations ADD CONSTRAINT FK_78AB76C9232D562B FOREIGN KEY (object_id) REFERENCES pages (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_translations ADD CONSTRAINT FK_6D8AA754232D562B FOREIGN KEY (object_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE page_translations DROP CONSTRAINT FK_78AB76C9232D562B');
        $this->addSql('ALTER TABLE post_translations DROP CONSTRAINT FK_6D8AA754232D562B');
        $this->addSql('DROP TABLE page_translations');
        $this->addSql('DROP TABLE post_translations');
    }
}
