<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210134826 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE post_tags (post_id INT NOT NULL, taxonomy_id INT NOT NULL, PRIMARY KEY (post_id, taxonomy_id))');
        $this->addSql('CREATE INDEX IDX_A6E9F32D4B89032C ON post_tags (post_id)');
        $this->addSql('CREATE INDEX IDX_A6E9F32D9557E6F6 ON post_tags (taxonomy_id)');
        $this->addSql('CREATE TABLE taxonomies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(64) NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_taxonomies_type ON taxonomies (type)');
        $this->addSql('CREATE UNIQUE INDEX uniq_taxonomies_type_slug ON taxonomies (type, slug)');
        $this->addSql('ALTER TABLE post_tags ADD CONSTRAINT FK_A6E9F32D4B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_tags ADD CONSTRAINT FK_A6E9F32D9557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomies (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE post_tags DROP CONSTRAINT FK_A6E9F32D4B89032C');
        $this->addSql('ALTER TABLE post_tags DROP CONSTRAINT FK_A6E9F32D9557E6F6');
        $this->addSql('DROP TABLE post_tags');
        $this->addSql('DROP TABLE taxonomies');
    }
}
